---
name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install packages
        run: |
          pip install -U \
            autopep8 flake8 flake8-bugbear flake8-isort pep8-naming .
      - name: Validate the codes using flake8
        run: |
          find . -type f -name '*.py' | xargs flake8
      - name: Test commands
        run: |
          tifft --version
          tifft --help
          tifft history --output-csv=fred.csv DJIA SP500 NASDAQ100
          tifft macd --output-csv=macd.csv SP500
          tifft bb --output-csv=bb.csv SP500
          tifft rsi --output-csv=rsi.csv SP500
